name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-output.outputs.commit_message }}
      branch_name: ${{ steps.set-output.outputs.branch_name }}
      commit_sha: ${{ steps.set-output.outputs.commit_sha }}
      commit_message: ${{ steps.set-output.outputs.commit_message }}
      commit_user: ${{ steps.set-output.outputs.commit_user }}
      commit_user_email: ${{ steps.set-output.outputs.commit_user_email }}

    steps:
      - name: Store build timestamp
        run: echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV

      - name: Deploy using stored timestamp
        run: echo "Deploying at $BUILD_TIME"

      # Step 1: Check out the main branch
      - name: Checkout main branch
        uses: actions/checkout@v4
#        with:
#          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Print Git info
        id: set-output
        run: |
            echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
            echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
            echo "commit_user=$(git log -1 --pretty=%cn)" >> $GITHUB_OUTPUT
            echo "commit_user_email=$(git log -1 --pretty=%ce)" >> $GITHUB_OUTPUT
      # Step 2: Run Helm package command
      - name: Build artifacts
        run: |
          make package-all

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: ./releases

  publish:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the release branch
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          ref: releases

      # Step 2: Download artifacts from the previous step
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: ./

      # Step 3: Run Helm repo index command
      - name: Publish Helm chart
        run: |
          ls -ltr
          helm repo index . --url https://github.com/meshkat632/helm-charts --merge index.yaml
          echo "#########################################################################"
          cat index.yaml

      - name: Print Git info
        run: |
          echo "#########################################################################"
          echo "Branch Name: ${{ needs.build-artifacts.outputs.image }}"
          echo "Commit SHA: ${{ env.commit_sha }}"
          echo "Commit Message: ${{ env.commit_message }}"
          echo "Commit User: ${{ env.commit_user }}"
          echo "Commit User Email: ${{ env.commit_user_email }}"
          echo "#########################################################################"
          
          git config --global user.email "meshkat632@gmail.com"
          git config --global user.name "Meshkatul Anwer"
          echo "Branch Name: $(git rev-parse --abbrev-ref HEAD)"
          echo "Commit SHA: $(git rev-parse --short HEAD)"
          git status
          git add .
          git commit -m "make helm releases"
          git push
