name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Build the static site (if applicable)
      - name: Build static site
        run: |
          mkdir -p ./dist
          echo "$(date)" > ./dist/index.html
          echo "hello, world!"

      # Step 5: Deploy to GitHub Pages
      #- name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      #    publish_dir: ./dist

      # Step 2: Switch to the `releases` branch
      - name: Checkout releases branch
        run: |
          git fetch origin releases
          git checkout -B releases origin/releases || git checkout --orphan releases

      # Step 3: Update the `index.html` file
      - name: Update index.html
        run: |
          mkdir -p ./dist
          echo "$(date)" > ./dist/index.html
          echo "hello, world!" >> ./dist/index.html
          cp -R ./dist/* .

      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config user.name "meshkat632@gmail.com"
          git config user.email "meshkat632@gmail.com"
      # Step 4: Commit and push changes to the `releases` branch
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |
          git add index.html
          git commit -m "Update index.html with the latest release"
          git push origin releases --force
