name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      # Step 2: Run Helm package command
      - name: Build artifacts
        run: |
          mkdir -p ./dist
          helm package ./chart -d ./dist
