name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main branch
      - name: Checkout main branch
        uses: actions/checkout@v4
#        with:
#          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Print Git info
        run: |
          echo "Branch Name: $(git rev-parse --abbrev-ref HEAD)"
          echo "Commit SHA: $(git rev-parse --short HEAD)"
      # Step 2: Run Helm package command
      - name: Build artifacts
        run: |
          make package-all
          make update-index

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: ./releases

  publish:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the release branch
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          ref: releases

      # Step 2: Download artifacts from the previous step
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: ./

      # Step 3: Run Helm repo index command
      - name: Publish Helm chart
        run: |
          ls -ltr
          helm repo index . --url https://github.com/meshkat632/helm-charts --merge index.yaml
          echo "#########################################################################"
          cat index.yaml

      - name: Print Git info
        run: |
          git config --global user.email "meshkat632@gmail.com"
          git config --global user.name "Meshkatul Anwer"
          echo "Branch Name: $(git rev-parse --abbrev-ref HEAD)"
          echo "Commit SHA: $(git rev-parse --short HEAD)"
          git status
          git add .
          git commit -m "Update Helm chart index.yaml"
          git push
