name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      # Step 2: Switch to the `releases` branch
      - name: Checkout releases branch
        run: |
          git fetch origin releases || echo "No releases branch exists yet."
          git checkout -B releases origin/releases || git checkout --orphan releases

      # Step 3: Update the `index.html` file
      - name: Update index.html
        run: |
          mkdir -p ./dist
          echo "$(date)" > ./dist/index.html
          echo "hello, world!" >> ./dist/index.html
          cp -R ./dist/* .

      # Step 4: Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # Step 5: Commit and push changes to the `releases` branch
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Update index.html with the latest release"
          git push https://x-access-token:${{ secrets.RELEASE_GITHUB_TOKEN }}@github.com/${{ github.repository }} releases --force
